"""added relationship of book to borrows table

Revision ID: 3ff4aef0b3dd
Revises: 2f4c328a6c9e
Create Date: 2025-07-25 12:55:14.491245

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3ff4aef0b3dd'
down_revision: Union[str, Sequence[str], None] = '2f4c328a6c9e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
